### PR TITLE
style: add style to Invite page

### PR DESCRIPTION
**Pull request by sugarpusher**
TODO: add action to "Renew link" button

### CODE REVIEW

**Review by agazso — APPROVED** [review]
Looks good!

For now we can remove the Renew button, see:
https://github.com/logos-innovation-lab/waku-objects-playground/issues/141

**Comment by sugarpusher** [comment]
Perfect, removed. Thanks!

**Review by agazso — APPROVED** [review]
:+1:

**Comment by sugarpusher** [comment]
@agazso thanks for the review 😊
If you think it's good to merge, do you mind merging it? I don't have permission 😉
Thanks!

**Comment by vojtechsimetka** [comment]
@sugarpusher wait, thats weird... I'll give you permissions.

**Pull request merged**
