### PR TITLE
feat: details view on waku object

### PR DESCRIPTION
**Pull request by vojtechsimetka**
Part of #125

View in chat with icon that can be expanded
Screenshot 2023-08-04 at 18 01 07

Detail view
Screenshot 2023-08-04 at 18 01 01

### CODE REVIEW

**Comment by sugarpusher** [comment]
I also can't click the details button from the recipient's bubble

**Comment by agazso** [comment]
I tested and found some issues:
- [ ] the details page layout seems to be broken (also on your picture, but I attached one to clarify what I refer to)
- [ ] reloading the details page results in 500 Internal error
- [ ] I think by design the gray area on the widget is clickable, not just the icon. Otherwise the icon is too small, so the click area should be larger (for phones)
- [ ] I get plenty of Zod errors when I close the details page (see screenshot)

For me clicking the recipient details button worked.

Screenshot from 2023-08-04 18-26-55

Screenshot from 2023-08-04 18-32-21

**Comment by agazso** [comment]
And to clarify, I would only investigate the Zod issue, the others are non-blockers. It would be good to open issues for them though.

**Comment by vojtechsimetka** [comment]
The Zod issues are there because you have some existing paygy transactions and the paygy store has changed (it now has 2 extra fields) Thats why it complains and the old paygy fail to render.

**Review by agazso — APPROVED** [review]

**Pull request merged**
