### PR TITLE
feat: heic image support

### LINKED ISSUE #430: Missing error when uploading HEIC profile picture
When creating a new identity, I tried to upload a HEIC image as a profile. It was not supported, nothing happened but I should have an error/info about it

### PR DESCRIPTION
**Pull request by vojtechsimetka**
Resolves #430 

We have to lazy-load the library as it only works in browser. That's why there is:
```ts
	const heic2any = await import('heic2any')
	const out = await heic2any.default({
		blob: heicFile,
		toType: 'image/png',
	})
```

### CODE REVIEW

**Comment by vojtechsimetka** [comment]
It works now even for that image. Did not know these can also be `image/heif` I thought just `image/heic`

**Comment by agazso** [comment]
> It works now even for that image. Did not know these can also be `image/heif` I thought just `image/heic`

I don't get an error now, but nothing happens when I try to set the linked HEIC image as my profile picture. Does it work for you?

**Comment by michelleplur** [comment]
does it also scale down the image to a smaller filesize?

**Comment by vojtechsimetka** [comment]
Yeah it scales them down and it may take quite some time. We should show some loading. The linked `heic` works for me 
Screenshot 2023-09-25 at 22 09 54

**Comment by agazso** [comment]
Well, it does not work for me neither in Firefox or Chrome. But I guess if it works on iOS Safari then it's okay.

**Comment by vojtechsimetka** [comment]
It works in chrome for me

**Comment by vojtechsimetka** [comment]
@agazso please try again now, I read up a bit on heic/heif and I missed on condition checking `heif` type

**Review by agazso — APPROVED** [review]
It works!

**Pull request merged**
