### PR TITLE
feat: link support in chat

### PR DESCRIPTION
**Pull request by agazso**

### CODE REVIEW

**Comment by sugarpusher** [comment]
I noticed that unless I start with `http://`, the link doesn't work - it thinks I'm looking for a relative path and I get a "Chat not found" error. Maybe we can make it work when starting the link with `www.`?

**Comment by agazso** [comment]
> I noticed that unless I start with `http://`, the link doesn't work - it thinks I'm looking for a relative path and I get a "Chat not found" error. Maybe we can make it work when starting the link with `www.`?

Thanks for catching this. I added a library that should handle all cases and also some tests.

**Review by vojtechsimetka — APPROVED** [review]
nice, works great! :)

**Comment by agazso** [comment]
Because of the errors in the preview closing this and using #293 instead

**Pull request closed without merging**
